const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function backend(){
 const code=fs.readFileSync(path.join(root,'workers/meta-collector/entry.js'),'utf8');
 const c={Request,Response,Headers,URL,URLSearchParams,TextEncoder,TextDecoder,AbortSignal,crypto:require('node:crypto').webcrypto,btoa,atob,console:{log(){},error(){}},fetch:async()=>new Response('[]'),setTimeout,clearTimeout};
 vm.createContext(c);vm.runInContext(code.replace('export default {','globalThis.moduleDefault = {')+'\nglobalThis.T={advanceProgress,expectedRounds,inspectSchema,optionalGet,activeTargets,campIndex,uniqueCandidateGroups,ensureBatches,runCollector,processBatch,worker,metaPost,storeFreshRows};',c);
 c.override=(name,value)=>{c.__replacement=value;vm.runInContext(name+'=globalThis.__replacement',c);};
 return c;
}
const env={SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-key',CAMP_DIRECTORY:{listCamps:async()=>[{camp:'Test Camp',code:'T001',mb_camp:'\ubcf8\ucea0\ud504'}]}};
function snapshot(c,prev,scanned,completed,time,extras={}){
 const d={assigned:0,scanned,completed,impossible:0,pdd:0,total:scanned+completed,...extras};
 const result=c.T.advanceProgress(prev,d,null,{pending:0,collected:0,uncollected:0},{wave:'WAVE1'},time);
 const row={...prev,delivery_assigned:d.assigned,delivery_scanned:scanned,delivery_completed:completed,delivery_total:d.total,
   delivery_impossible:d.impossible,delivery_pdd_miss:d.pdd,current_round:result.currentRound,last_seen_at:time,last_progress_at:result.lastProgressAt,
   exact_complete_candidate_at:result.exactCandidate,work_completed_at:result.workCompletedAt,completion_method:result.completionMethod,completion_detected_at:result.completionDetectedAt};
 for(let i=1;i<=3;i++){const r=result.rounds[i];Object.assign(row,{['round'+i+'_scan_started_at']:r.scan,['round'+i+'_delivery_started_at']:r.delivery,['round'+i+'_completed_at']:r.completed,['round'+i+'_completion_detected_at']:r.detected,['round'+i+'_completion_method']:r.method});}
 return row;
}
test('night expected_rounds=3 even if old batch says 2',()=>{const c=backend();assert.equal(c.T.expectedRounds({wave:'WAVE1',expected_rounds:2}),3);assert.equal(c.T.expectedRounds({wave:'WAVE2'}),2);});
test('real schema reads succeed WITHOUT manual approval flag',async()=>{const c=backend(),paths=[];c.override('sb',async(e,p)=>{paths.push(p);return [];});const r=await c.T.inspectSchema(env);assert.equal(r.ready,true);assert.equal(paths.length,6);assert(paths.every(p=>p.endsWith('&limit=0')));});
test('missing required column reports actual table error',async()=>{const c=backend();c.override('sb',async(e,p)=>{if(p.startsWith('meta_realtime_current'))throw Object.assign(new Error('column round3_delivery_started_at does not exist'),{code:'42703',status:400});return [];});const r=await c.T.inspectSchema(env);assert.equal(r.ready,false);assert.equal(r.issues[0].table,'meta_realtime_current');});
test('missing OPTIONAL schedule table does not block collection',async()=>{const c=backend();c.override('sb',async()=>{throw Object.assign(new Error('not found'),{code:'PGRST205'});});assert.equal((await c.T.optionalGet(env,'tonest_schedule?select=*')).length,0);});
test('optional table auth errors are NOT silently swallowed',async()=>{const c=backend();c.override('sb',async()=>{throw Object.assign(new Error('permission denied'),{code:'42501',status:403});});await assert.rejects(c.T.optionalGet(env,'tonest_schedule?select=*'),/permission denied/);});
test('discovery works with no schedules and no registered driver records',async()=>{
 const c=backend(),saved=[];c.override('activeTargets',()=>[{date:'2026-10-09',wave:'WAVE1'}]);
 c.override('metaPost',async(cookies,url,payload)=>{assert.equal(payload.workDate,'2026-10-10');return {success:true,body:{data:{content:[{campInfo:{campCode:'T001',campName:'Test Camp'}}]}}};});
 c.override('sb',async(e,p,init={})=>{if(p.startsWith('meta_backend_state'))return [{collector_paused:false}];if(p.startsWith('tonest_schedule'))return [];if(p.startsWith('meta_realtime_batch')&&init.method==='POST'){saved.push(...JSON.parse(init.body));return [];}return [];});
 const result=await c.T.ensureBatches(env,new Map(),[]);assert.equal(saved.length,1);assert.equal(saved[0].expected_rounds,3);assert.equal(saved[0].camp_code,'T001');assert.equal(result[0].source,'META_WITHOUT_SCHEDULE');
});
test('directory seeds work even when META camp summary is empty',async()=>{const c=backend(),saved=[];c.override('activeTargets',()=>[{date:'2026-10-09',wave:'WAVE1'}]);c.override('metaPost',async()=>({success:true,body:{data:{content:[]}}}));c.override('sb',async(e,p,init={})=>{if(p.startsWith('meta_backend_state'))return [{collector_paused:false}];if(init.method==='POST')saved.push(...JSON.parse(init.body));return [];});await c.T.ensureBatches(env,new Map(),[{camp_code:'Test Camp',wave:'\uc57c\uac04',is_resigned:false}]);assert.equal(saved.length,1);});
test('master mobile/base aliases form one camp batch',()=>{const c=backend();const index=c.T.campIndex([{camp:'A',code:'SG01'},{camp:'A',code:'T001',mb_camp:'\ubcf8\ucea0\ud504'}]);const x=c.T.uniqueCandidateGroups([{campCode:'S601'},{campCode:'T001'}],[],index);assert.equal(x.groups.length,1);assert.equal(x.groups[0].code,'T001');});
test('night active date crosses midnight in KST',()=>{const c=backend();const targets=c.T.activeTargets(new Date('2026-10-10T02:00:00+09:00'));assert.equal(targets[0].date,'2026-10-09');assert.equal(targets[0].wave,'WAVE1');});
test('rounds 1 and 2 do not finish night work; round3 does',()=>{
 const c=backend();let r=snapshot(c,null,10,0,'2026-10-09T20:00:00');
 r=snapshot(c,r,0,10,'2026-10-09T20:10:00');r=snapshot(c,r,0,10,'2026-10-09T20:11:00');assert(r.round1_completed_at);assert.equal(r.work_completed_at,null);
 r=snapshot(c,r,10,10,'2026-10-09T23:00:00');assert.equal(r.current_round,2);
 r=snapshot(c,r,0,20,'2026-10-09T23:20:00');r=snapshot(c,r,0,20,'2026-10-09T23:21:00');assert(r.round2_completed_at);assert.equal(r.work_completed_at,null);
 r=snapshot(c,r,10,20,'2026-10-10T01:00:00');assert.equal(r.current_round,3);
 r=snapshot(c,r,0,30,'2026-10-10T02:00:00');r=snapshot(c,r,0,30,'2026-10-10T02:01:00');assert(r.work_completed_at);assert.equal(r.round3_delivery_started_at,'2026-10-10T02:00:00');
 r=snapshot(c,r,1,30,'2026-10-10T02:02:00');assert.equal(r.work_completed_at,null);assert.equal(r.round3_completed_at,null);
});
test('cancellation and PDD are not the first actual delivery',()=>{const c=backend();const r=snapshot(c,null,0,0,'2026-10-09T20:00:00',{impossible:5,pdd:1,total:6});assert.equal(r.round1_delivery_started_at,null);assert.equal(r.work_completed_at,null);});
test('assignments alone do not advance rounds',()=>{const c=backend();let r=snapshot(c,null,10,0,'2026-10-09T20:00:00');r=snapshot(c,r,0,10,'2026-10-09T20:10:00');r=snapshot(c,r,0,10,'2026-10-09T20:11:00');r=snapshot(c,r,0,10,'2026-10-09T20:12:00',{assigned:20,total:30});assert.equal(r.current_round,1);});
test('paused run does not validate or call META',async()=>{const c=backend();let validations=0;c.override('sessionState',async()=>({collector_paused:true}));c.override('inspectSchema',async()=>{validations++;throw new Error('should not read schema');});const result=await c.T.runCollector(env,true);assert.equal(result.paused,true);assert.equal(validations,0);});
test('unauthenticated collection control is rejected',async()=>{const c=backend();const r=await c.T.worker.fetch(new Request('https://worker.test/collector/control',{method:'POST',body:'{"paused":true}'}),env,{});assert.equal(r.status,401);});
test('GET cannot change collection state',async()=>{const c=backend();const r=await c.T.worker.fetch(new Request('https://worker.test/collector/control'),env,{});assert.equal(r.status,405);});
test('team leader cannot stop server collection',async()=>{const c=backend();c.fetch=async()=>new Response(JSON.stringify({id:'u'}));c.override('sb',async()=>[{role:'team_leader',status:'active'}]);const r=await c.T.worker.fetch(new Request('https://worker.test/collector/control',{method:'POST',headers:{authorization:'Bearer USER'},body:'{"paused":true}'}),env,{});assert.equal(r.status,403);});
test('stop uses existing user-scoped RPC and works with broken schema',async()=>{const c=backend();let paused=false,delegated=false;c.fetch=async(url,init)=>{if(url.endsWith('/auth/v1/user'))return new Response('{"id":"u"}');if(url.endsWith('/rpc/tn_set_meta_collector_paused')){assert.equal(init.headers.authorization,'Bearer USER');assert.equal(JSON.parse(init.body).p_paused,true);delegated=true;paused=true;return new Response('true');}throw new Error('unexpected URL');};c.override('sb',async(e,p)=>p.startsWith('profiles')?[{role:'super_admin',status:'active'}]:[{collector_paused:paused,status:'expired'}]);c.override('inspectSchema',async()=>{throw new Error('must not validate during stop');});const r=await c.T.worker.fetch(new Request('https://worker.test/collector/control',{method:'POST',headers:{authorization:'Bearer USER'},body:'{"paused":true}'}),env,{});assert.equal(r.status,200);assert(delegated);assert.equal((await r.json()).paused,true);});
test('resume blocked with specific schema errors instead of manual flag',async()=>{const c=backend();c.fetch=async()=>new Response('{"id":"u"}');c.override('sb',async()=>[{role:'super_admin',status:'active'}]);c.override('inspectSchema',async()=>({ready:false,issues:[{table:'meta_realtime_current',message:'column missing'}]}));const r=await c.T.worker.fetch(new Request('https://worker.test/collector/control',{method:'POST',headers:{authorization:'Bearer USER'},body:'{"paused":false}'}),env,{});assert.equal(r.status,409);assert.equal((await r.json()).schema.issues.length,1);});
test('pause after upstream request prevents new current snapshots',async()=>{const c=backend(),writes=[];let checks=0;c.override('assertCollecting',async()=>{if(++checks===2)throw Object.assign(new Error('COLLECTOR_PAUSED'),{code:'COLLECTOR_PAUSED'});});c.override('metaPost',async()=>({success:true,body:{data:{content:[{workerInfo:{workerName:'Test',coupangId:'test',workSubRoutes:['126A01']},deliverySummary:{scannedCount:1}}]}}}));c.override('sb',async(e,p,init)=>{if(init?.method==='POST')writes.push(p);return [];});await assert.rejects(c.T.processBatch(env,new Map(),{id:'batch',camp_code:'T001',camp_name:'Test Camp',wave:'WAVE1',schedule_date:'2026-10-09',meta_work_date:'2026-10-10'},[]),/COLLECTOR_PAUSED/);assert.equal(writes.length,0);});
test('unscheduled META driver is saved with actual name and no false route alerts',async()=>{const c=backend(),writes=[];c.override('metaPost',async()=>({success:true,body:{data:{content:[{workerInfo:{workerName:'Test Driver',coupangId:'actual',workSubRoutes:['126A01']},deliverySummary:{scannedCount:7,completedCount:3}}]}}}));c.override('sb',async(e,p,init)=>{if(p.startsWith('meta_backend_state'))return [{collector_paused:false}];if(init?.method==='POST'){writes.push({p,body:JSON.parse(init.body)});return JSON.parse(init.body);}return [];});await c.T.processBatch(env,new Map(),{id:'b',camp_code:'T001',camp_name:'Test Camp',wave:'WAVE1',schedule_date:'2026-10-09',meta_work_date:'2026-10-10'},[]);const current=writes.find(r=>r.p.startsWith('meta_realtime_current')).body[0];assert.equal(current.driver_name,'Test Driver');assert.equal(current.coupang_id,'actual');assert.equal(current.expected_rounds,3);assert.equal(current.raw_payload.route_alerts.length,0);assert.equal(current.delivery_total,10);});
function frontend(){const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',disabled:false,title:'',className:'',classList:{toggle(){},add(){},remove(){}},querySelectorAll:()=>[]});return elements.get(id);};const c={window:{},document:{getElementById:el},localStorage:{getItem:()=>null,setItem(){}},console:{log(){},warn(){},error(){}},Date,Intl,URL,Headers,Request,Response,AbortSignal,setTimeout(){},clearTimeout(){},clearInterval(){},confirm:()=>true};vm.createContext(c);let code=[...fs.readFileSync(path.join(root,'public/realtime'),'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');code=code.replace('boot();','globalThis.T={S,buildCamps,renderAll,doneAt,mergeFresh,metricCollection,queryAll,toggleCollector,renderCollectorState,fmtClock};globalThis.override=(k,v)=>{if(k==="api")api=v;if(k==="readAll")readAll=v;};');vm.runInContext(code,c);c.el=el;return c;}
test('dashboard renders three night start times, final badge only for round3',()=>{const c=frontend(),t=c.T;t.S.rows=[1,2,3].map(round=>({batch_id:'b',camp_name:'Camp',wave:'WAVE1',driver_name:'Driver '+round,delivery_total:10,delivery_completed:5,delivery_scanned:5,scan_started_at:'2026-10-09T20:00:00',current_round:round,work_completed_at:'2026-10-10T03:00:00',round3_delivery_started_at:round===3?'2026-10-10T02:00:00':null}));t.S.camps=t.buildCamps();t.renderAll();const html=c.el('driverBody').innerHTML;assert.equal((html.match(/class="driverCard"/g)||[]).length,3);assert.equal((html.match(/class="doneBadge"/g)||[]).length,1);assert.equal((html.match(/3\ucc28\ubc30\uc1a1/g)||[]).length,3);});
test('no schedule is displayed as unknown, not zero absent drivers',()=>{const c=frontend(),t=c.T;t.S.rows=[{batch_id:'b',camp_name:'Camp',wave:'WAVE1',driver_name:'D',delivery_total:10,delivery_scanned:10}];t.S.camps=t.buildCamps();t.renderAll();assert.match(c.el('campBody').innerHTML,/\uc2a4\ucf00\uc904 \uc5c6\uc74c/);});
test('fresh merge uses stable PK and preserves zeros',()=>{const t=frontend().T;const rows=t.mergeFresh([{batch_id:'b',driver_pk:1,meta_worker_key:'old',fresh_delivery_total:7}],[{batch_id:'b',driver_pk:1,meta_worker_key:'new',delivery_total:0}]);assert.equal(rows[0].fresh_delivery_total,0);});
test('return absent count is not counted twice',()=>{const t=frontend().T;const m=t.metricCollection({return_pending:1,return_collected:2,return_uncollected_raw:3,return_absent_raw:3},'return',true);assert.equal(m.total,6);});
test('UTC source timestamp is displayed in KST',()=>{assert.equal(frontend().T.fmtClock('2026-10-09T12:00:00Z'),'21:00');});
test('UI refresh loads META rows even when schedule table is absent',async()=>{const c=frontend(),t=c.T;const date=new Date(Date.now()+9*3600000).toISOString().slice(0,10);c.override('api',async()=>({ok:true,state:{status:'active',paused:false},schema:{ready:true},batches:[]}));c.override('readAll',async(table)=>{if(table==='tonest_schedule')throw Object.assign(new Error('not found'),{code:'PGRST205'});if(table==='meta_realtime_batch')return [{id:'b',schedule_date:date,wave:'WAVE2',status:'collecting'}];if(table==='meta_realtime_current')return [{batch_id:'b',schedule_date:date,wave:'WAVE2',camp_name:'Camp',driver_name:'META driver',delivery_total:10,delivery_scanned:10}];return [];});await t.queryAll();assert.equal(t.S.rows.length,1);assert.equal(t.S.camps.length,1);assert.equal(t.S.scheduleAvailable,false);});
test('UI pause toggle does not clear visible rows',async()=>{const c=frontend(),t=c.T;t.S.isAdmin=true;t.S.collectorPaused=false;t.S.rows=[{driver_name:'keep'}];const calls=[];c.override('api',async(path,opts)=>{calls.push({path,opts});return {ok:true,paused:true,state:{status:'active',paused:true},schema:{ready:true},batches:[]};});await t.toggleCollector();assert.equal(calls[0].path,'/collector/control');assert.equal(calls[0].opts.body.paused,true);assert.equal(t.S.rows[0].driver_name,'keep');assert.equal(t.S.collectorPaused,true);});
test('read-only manager has disabled server toggle',()=>{const c=frontend(),t=c.T;t.S.isAdmin=false;t.S.collectorPaused=false;t.renderCollectorState();assert.equal(c.el('collectorToggleBtn').disabled,true);});
