name = "meta-direct-poc"
main = "entry.js"
compatibility_date = "2026-10-06"
keep_vars = true
workers_dev = true
preview_urls = false

[triggers]
crons = ["* * * * *", "*/5 * * * *"]

[[services]]
binding = "CAMP_DIRECTORY"
service = "coupang-camps"
entrypoint = "RealtimeCampDirectory"

[observability]
enabled = true
